// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppOpenLevelDB
SEXP cppOpenLevelDB(const std::string& path, const bool create);
RcppExport SEXP RLevelDB_cppOpenLevelDB(SEXP pathSEXP, SEXP createSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const bool >::type create(createSEXP);
    __result = Rcpp::wrap(cppOpenLevelDB(path, create));
    return __result;
END_RCPP
}
// cppDbGet
Rcpp::CharacterVector cppDbGet(SEXP xp, const std::vector<std::string>& keys);
RcppExport SEXP RLevelDB_cppDbGet(SEXP xpSEXP, SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type keys(keysSEXP);
    __result = Rcpp::wrap(cppDbGet(xp, keys));
    return __result;
END_RCPP
}
// cppDbPut
void cppDbPut(SEXP xpt, const std::vector<std::string>& keys, const std::vector<std::string>& values, const bool sync);
RcppExport SEXP RLevelDB_cppDbPut(SEXP xptSEXP, SEXP keysSEXP, SEXP valuesSEXP, SEXP syncSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xpt(xptSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type keys(keysSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const bool >::type sync(syncSEXP);
    cppDbPut(xpt, keys, values, sync);
    return R_NilValue;
END_RCPP
}
// cppDbDelete
void cppDbDelete(SEXP xpt, const std::vector<std::string>& keys, const bool sync);
RcppExport SEXP RLevelDB_cppDbDelete(SEXP xptSEXP, SEXP keysSEXP, SEXP syncSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xpt(xptSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type keys(keysSEXP);
    Rcpp::traits::input_parameter< const bool >::type sync(syncSEXP);
    cppDbDelete(xpt, keys, sync);
    return R_NilValue;
END_RCPP
}
