# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RLevelDB
#' @importFrom Rcpp evalCpp
NULL

cppOpenLevelDB <- function(path, create) {
    .Call('RLevelDB_cppOpenLevelDB', PACKAGE = 'RLevelDB', path, create)
}

cppDbGet <- function(xp, keys) {
    .Call('RLevelDB_cppDbGet', PACKAGE = 'RLevelDB', xp, keys)
}

cppDbPut <- function(xpt, keys, values, sync) {
    invisible(.Call('RLevelDB_cppDbPut', PACKAGE = 'RLevelDB', xpt, keys, values, sync))
}

cppDbDelete <- function(xpt, keys, sync) {
    invisible(.Call('RLevelDB_cppDbDelete', PACKAGE = 'RLevelDB', xpt, keys, sync))
}

